### ISSUE TITLE
The shadow never fully disappears

### ISSUE THREAD

**Issue by yched** [stefanjudis/css-scroll-shadows#3]
Thanks for the neat tool !

Small issue though : when the scrollable container is scrolled all the way to the top, the top shadow is supposed to be absent, but its lower part still shows.

See the grey smear here :
![image](https://user-images.githubusercontent.com/193080/85837745-c23e5b80-b798-11ea-9175-b75930029875.png)

(Tried on Chrome 83 & Firefox 77)

**Comment by stefanjudis** [comment]
Thanks Yves, you're right! That should be quickly fixed, would you be up for PR'ing? 😊

**Comment by yched** [comment]
Hmm, I haven't really figured out how the trick works (no CSS expert here), so not sure about that :grin:

**Comment by stefanjudis** [comment]
No prob, completely udnerstand. Let's see, have to say, for me this bug is low prio. 

[The linked article](https://lea.verou.me/2012/04/background-attachment-local/) explains how it works, if you're up for becoming a CSS expert. :)

**Comment by yched** [comment]
OK, I think I got it :
if you adjust the linear-gradient steps from 30% / 70% to 33% / 66%, and then change their height from 2x to 3x the height of the circular-gradient, then it seems to hide fully when needed

that is, from currently

```css
.scrollGradient {
  background: 
    linear-gradient(#a9fcc2 30%, rgba(169,252,194, 0)),
    linear-gradient(rgba(169,252,194, 0), #a9fcc2 70%) 0 100%,
    radial-gradient(farthest-side at 50% 0, rgba(34,34,34, 0.5), rgba(0,0,0,0)),
    radial-gradient(farthest-side at 50% 100%, rgba(34,34,34, 0.5), rgba(0,0,0,0)) 0 100%;
  background-color: #a9fcc2;
  background-repeat: no-repeat;
  background-attachment: local, local, scroll, scroll;
  background-size: 100% 30px, 100% 30px, 100% 15px, 100% 15px;
}
```
to 
```css
.scrollGradient {
  background: 
    linear-gradient(#a9fcc2 33%, rgba(169,252,194, 0)),
    linear-gradient(rgba(169,252,194, 0), #a9fcc2 66%) 0 100%,
    radial-gradient(farthest-side at 50% 0, rgba(34,34,34, 0.5), rgba(0,0,0,0)),
    radial-gradient(farthest-side at 50% 100%, rgba(34,34,34, 0.5), rgba(0,0,0,0)) 0 100%;
  background-color: #a9fcc2;
  background-repeat: no-repeat;
  background-attachment: local, local, scroll, scroll;
  background-size: 100% 45px, 100% 45px, 100% 15px, 100% 15px;
}
```

I'll try to see if I can translate that to a PR
